"""rbac_user_features

Revision ID: 15b4c05ba38d
Revises: 001_initial
Create Date: 2026-09-03 20:42:19.761525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '15b4c05ba38d'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('page_selection', sqlite.JSON(), nullable=True),
    sa.Column('position', sqlite.JSON(), nullable=True),
    sa.Column('position_rest', sqlite.JSON(), nullable=True),
    sa.Column('position_mode', sa.String(length=32), nullable=False, server_default='single'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_user_id'), 'presets', ['user_id'], unique=False)
    op.create_table('user_logos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('thumb_key', sa.String(length=500), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logos_user_id'), 'user_logos', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('mode', sa.String(length=32), nullable=False, server_default='multiple_pdfs'))
    op.add_column('jobs', sa.Column('logo_keys', sqlite.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('logo_names', sqlite.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('source_names', sqlite.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('is_password_set', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('avatar_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_thumb_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # NOTE: the previous version of this migration seeded an admin account
    # ("dev@logofier.com.br") with an empty password. That backdoor was removed;
    # existing deployments are cleaned up by 09_remove_seeded_admin. New
    # databases must use scripts/create_admin.py to bootstrap admins.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'avatar_thumb_key')
    op.drop_column('users', 'avatar_key')
    op.drop_column('users', 'is_password_set')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_column('jobs', 'deleted_at')
    op.drop_column('jobs', 'title')
    op.drop_column('jobs', 'source_names')
    op.drop_column('jobs', 'logo_names')
    op.drop_column('jobs', 'logo_keys')
    op.drop_column('jobs', 'mode')
    op.drop_index(op.f('ix_user_logos_user_id'), table_name='user_logos')
    op.drop_table('user_logos')
    op.drop_index(op.f('ix_presets_user_id'), table_name='presets')
    op.drop_table('presets')
    # ### end Alembic commands ###
